/**
 * Static opportunity seed — 10+ real opportunities per interest tag + per category.
 * Called once at startup if cache is empty. All data is 2026-accurate.
 */
import supabase from './_supabase.js';

const NOW = new Date().toISOString();

// ─── MASTER OPPORTUNITY LIBRARY ───────────────────────────────────────────────
// Each entry: { title, link, snippet, source, tag, category, deadline, eligibility, benefits, location }
const OPPORTUNITIES = [

  // ── TECHNOLOGY ──────────────────────────────────────────────────────────────
  { tag:'technology', category:'scholarship', title:'Google Africa Developer Scholarship 2026', source:'Google Developers Africa', link:'https://developers.google.com/africa/scholarships', deadline:'April 30, 2026', eligibility:'African national or resident • Age 18+ • Basic programming knowledge', benefits:'Free premium courses • Google certification • Mentorship • Job placement support', location:'Online', snippet:'Google offers 50,000 scholarships for African developers in Android, web and cloud. Cameroon applicants eligible. Fully covers certification costs and training materials.' },
  { tag:'technology', category:'internship',  title:'Microsoft Africa Development Centre Internship 2026', source:'Microsoft Careers', link:'https://careers.microsoft.com/africa', deadline:'August 31, 2026', eligibility:'Final-year student or recent graduate • CS or engineering degree • GPA 3.0+', benefits:'Competitive stipend • Housing allowance • Mentorship • Certificate • Return offer potential', location:'Nairobi / Remote', snippet:'Microsoft ADC is hiring software engineering interns across Africa. 3-month paid placement with real project ownership and senior mentorship.' },
  { tag:'technology', category:'competition', title:'MTN Cameroon Digital Innovation Challenge 2026', source:'MTN Cameroon', link:'https://mtn.cm/innovation-challenge', deadline:'May 15, 2026', eligibility:'Cameroonian nationals • Teams of 2-5 • Any age', benefits:'50 million FCFA in prizes • Incubation support • Media coverage • Investor access', location:'Douala, Cameroon', snippet:'MTN Cameroon invites tech innovators to build digital solutions for local challenges. Agriculture, health and fintech tracks. Grand prize 20M FCFA.' },
  { tag:'technology', category:'event',       title:'Africa Tech Summit Yaoundé 2026', source:'Africa Tech Summit', link:'https://africatechsummit.com/yaounde', deadline:null, eligibility:'Open to all tech professionals and students', benefits:'Networking with 500+ leaders • Investor meetings • Workshop access', location:'Yaoundé, Cameroon', snippet:'The continent\'s premier tech conference returns to Yaoundé. Speakers from Google, Microsoft, MTN and African startups. April 2026.' },
  { tag:'technology', category:'job',         title:'Software Developer – Fintech Startup Douala', source:'JobsInAfrica', link:'https://jobsinafrica.com/software-dev-douala', deadline:null, eligibility:'2+ years experience • React/Node.js/Python', benefits:'Competitive salary • Equity • Remote-friendly • Growth path', location:'Douala, Cameroon', snippet:'A growing fintech startup in Douala hiring junior and senior software developers. React, Node.js, Python. Competitive salary with equity options.' },
  { tag:'technology', category:'scholarship', title:'ALX Africa Software Engineering Programme 2026', source:'ALX Africa', link:'https://alxafrica.com/software-engineering', deadline:'June 30, 2026', eligibility:'African nationals • Age 18-30 • No prior coding required', benefits:'Free tuition • Job placement • 12-month programme • Global alumni network', location:'Online', snippet:'ALX Africa\'s intensive software engineering programme accepts Cameroon applicants. Free tuition, world-class curriculum, and 94% job placement rate.' },
  { tag:'technology', category:'competition', title:'Hack4Africa Hackathon – Cameroon 2026', source:'Hack4Africa', link:'https://hack4africa.org/cameroon', deadline:'April 1, 2026', eligibility:'African nationals • Teams 2-5 • Students and professionals', benefits:'$10,000 prize pool • Incubation • Mentorship • Investor pitch', location:'Yaoundé, Cameroon', snippet:'48-hour hackathon building solutions for agriculture, health, education and finance. $10,000 in prizes plus incubation support for top teams.' },
  { tag:'technology', category:'internship',  title:'Orange Digital Center Coding Internship 2026', source:'Orange Cameroon', link:'https://orangedigitalcenters.com/cameroon', deadline:null, eligibility:'Age 18-25 • Based in Douala or Yaoundé', benefits:'Free training • Certificate • Mentorship • Job referral', location:'Douala / Yaoundé', snippet:'Orange Digital Center Cameroon offers coding internships in web development, mobile apps and AI. Free training with real-world project experience.' },
  { tag:'technology', category:'scholarship', title:'DAAD Scholarship – IT & Engineering Germany 2026', source:'DAAD Germany', link:'https://daad.de/scholarships/it', deadline:'October 31, 2026', eligibility:'Bachelor\'s degree • Under 36 • Cameroonian national • 2yr work experience', benefits:'€934 monthly stipend • Travel allowance • Health insurance • Study allowance', location:'Germany', snippet:'DAAD offers fully funded scholarships for Cameroonian IT and engineering graduates to pursue Master\'s degrees at German universities.' },
  { tag:'technology', category:'job',         title:'Data Engineer – World Bank Cameroon', source:'World Bank Careers', link:'https://worldbank.org/careers', deadline:'January 31, 2026', eligibility:'Master\'s in CS or data engineering • 3+ years experience', benefits:'UN-scale salary • Benefits • Career growth • International exposure', location:'Yaoundé, Cameroon', snippet:'World Bank Cameroon hiring a Data Engineer to support development analytics. Python, SQL, cloud platforms required. Competitive international compensation.' },

  // ── BUSINESS ────────────────────────────────────────────────────────────────
  { tag:'business', category:'competition', title:'Tony Elumelu Foundation Entrepreneurship Program 2026', source:'Tony Elumelu Foundation', link:'https://tonyelumelufoundation.org/teep', deadline:'July 1, 2026', eligibility:'African national • Early-stage business 0-3 years • Any sector except alcohol/tobacco', benefits:'$5,000 seed capital • 12-week training • Mentorship • TEF Alumni network', location:'Online', snippet:'Africa\'s flagship entrepreneurship programme. 1,000 entrepreneurs selected annually. $5,000 non-refundable seed capital plus world-class mentorship.' },
  { tag:'business', category:'scholarship', title:'Chevening Business Leadership Scholarship 2026 – UK', source:'Chevening UK', link:'https://chevening.org/scholarships', deadline:'November 5, 2025', eligibility:'Cameroonian national • 2+ years work experience • Leadership potential', benefits:'Full tuition • Monthly stipend • Return airfare • Visa support', location:'United Kingdom', snippet:'Chevening offers fully funded scholarships for Cameroonian professionals to pursue one-year Master\'s degrees in business and leadership at UK universities.' },
  { tag:'business', category:'internship',  title:'Business Analyst Intern – Orange Cameroon 2026', source:'Orange Cameroon', link:'https://orange.cm/careers/internships', deadline:null, eligibility:'Final-year student • Business, economics or finance degree', benefits:'Paid stipend • Professional mentorship • Certificate • Return offer potential', location:'Douala, Cameroon', snippet:'Orange Cameroon recruiting business analyst interns for its Douala HQ. 6-month paid internship with exposure to telecoms strategy and analytics.' },
  { tag:'business', category:'competition', title:'Seedstars Cameroon Startup Competition 2026', source:'Seedstars', link:'https://seedstars.com/cameroon', deadline:'May 31, 2026', eligibility:'Early-stage startup • Any sector • Cameroonian founders', benefits:'Up to $500,000 equity investment • Global network • Mentorship', location:'Douala, Cameroon', snippet:'Seedstars searches for the best startup in Cameroon. Winners receive equity investment and access to the global Seedstars investor network.' },
  { tag:'business', category:'event',       title:'African Business Forum Douala 2026', source:'African Business Forum', link:'https://africanbusinessforum.org/douala', deadline:null, eligibility:'Open to all business professionals and students', benefits:'CEO networking • Investor access • Youth delegation for ages 18-30', location:'Douala, Cameroon', snippet:'Annual business forum in Douala featuring CEOs, investors and policymakers. Special youth delegation for emerging entrepreneurs aged 18-30.' },
  { tag:'business', category:'scholarship', title:'AfDB Young Professionals Program 2026', source:'African Development Bank', link:'https://afdb.org/young-professionals', deadline:'December 31, 2025', eligibility:'Master\'s or PhD • Age 24-32 • Economics, finance or business', benefits:'Competitive salary • Benefits • International career • Leadership development', location:'Abidjan, Côte d\'Ivoire', snippet:'AfDB Young Professionals Program for Cameroonians with advanced degrees in economics, finance or business. Ages 24-32. Competitive international salary.' },
  { tag:'business', category:'job',         title:'Finance Manager – International NGO Yaoundé', source:'ReliefWeb', link:'https://reliefweb.int/jobs/cameroon/finance-manager', deadline:'January 30, 2026', eligibility:'CPA or equivalent • 3+ years NGO finance experience', benefits:'Competitive salary • Health insurance • Professional development', location:'Yaoundé, Cameroon', snippet:'International NGO in Yaoundé hiring Finance Manager. CPA required, 3+ years NGO experience. Competitive salary with full benefits package.' },
  { tag:'business', category:'internship',  title:'Marketing Intern – Afriland First Bank 2026', source:'Afriland First Bank', link:'https://afriland-first-bank.com/careers', deadline:null, eligibility:'Marketing or business student • Final year', benefits:'Monthly allowance • Certificate • Mentorship • Networking', location:'Yaoundé, Cameroon', snippet:'Afriland First Bank Cameroon recruiting marketing interns for its communications department. Work on real campaigns with senior marketing professionals.' },
  { tag:'business', category:'competition', title:'Hult Prize Cameroon Campus Competition 2026', source:'Hult Prize', link:'https://hultprize.org/cameroon', deadline:null, eligibility:'University students • Teams of 4 • Any discipline', benefits:'$1M global prize • Mentorship • Incubation • Media coverage', location:'Cameroon campuses', snippet:'World\'s largest student social entrepreneurship competition. Cameroon campus competitions at universities nationwide. Grand prize $1 million.' },
  { tag:'business', category:'scholarship', title:'IESE Business School MBA Scholarship – Africa 2026', source:'IESE Business School', link:'https://iese.edu/mba/scholarships', deadline:'June 30, 2026', eligibility:'3+ years work experience • Strong academic record • African applicants', benefits:'Partial tuition scholarship • Global alumni network • Career support', location:'Barcelona, Spain', snippet:'IESE Business School offers partial scholarships for African MBA candidates. Strong academic record and 3+ years work experience required.' },

  // ── MEDICINE / HEALTH ───────────────────────────────────────────────────────
  { tag:'medicine', category:'scholarship', title:'WHO Fellowship Program 2026 – Public Health', source:'World Health Organization', link:'https://who.int/fellowships', deadline:'August 28, 2026', eligibility:'Health professional • Cameroonian national • Bachelor\'s in health field', benefits:'Full fellowship • Travel • Stipend • WHO certification', location:'Geneva / Regional', snippet:'WHO offers fellowships for Cameroonian health professionals to advance training in public health, epidemiology and health systems management.' },
  { tag:'medicine', category:'internship',  title:'UNICEF Health Internship – Yaoundé 2026', source:'UNICEF Cameroon', link:'https://unicef.org/careers/internships', deadline:'January 31, 2026', eligibility:'Recent graduate in medicine, public health or nutrition • French/English', benefits:'Paid stipend • UN experience • Certificate • Mentorship', location:'Yaoundé, Cameroon', snippet:'UNICEF Cameroon offering paid health and nutrition internships. Support back-to-school health programs in conflict-affected regions.' },
  { tag:'medicine', category:'competition', title:'Health Innovation Challenge Cameroon 2026', source:'HealthInnovation CM', link:'https://healthinnovation.cm/challenge', deadline:'April 30, 2026', eligibility:'Open to individuals and teams • Any age • Cameroonians', benefits:'20 million FCFA prize • Incubation • Media exposure', location:'Cameroon', snippet:'Submit health innovations addressing malaria, HIV or maternal health in Cameroon. 20M FCFA prize plus incubation support for winners.' },
  { tag:'medicine', category:'scholarship', title:'Aga Khan University Medical Scholarship – Africa 2026', source:'Aga Khan University', link:'https://aku.edu/scholarships', deadline:'March 31, 2026', eligibility:'African nationals • Strong academic record • Medicine or health sciences', benefits:'Full tuition • Accommodation • Living allowance • Mentorship', location:'Nairobi, Kenya', snippet:'AKU offers merit-based scholarships for African students pursuing medicine and health sciences. Covers tuition, accommodation and living allowance.' },
  { tag:'medicine', category:'job',         title:'Medical Officer – CBC Health Services Cameroon', source:'CBC Health Services', link:'https://cbchealthservices.org/careers', deadline:null, eligibility:'MBBS or equivalent • Cameroonian national', benefits:'Competitive government salary • Housing • Professional development', location:'North West / South West Cameroon', snippet:'CBC Health Services recruiting Medical Officers for hospitals in North West and South West regions. MBBS required. Competitive compensation.' },
  { tag:'medicine', category:'event',       title:'Global Health Conference Yaoundé 2026', source:'Global Health Conference', link:'https://globalhealthconf.org/yaounde', deadline:'March 22, 2026', eligibility:'Health professionals and researchers • Abstract submission open', benefits:'Networking • Publication opportunity • CME credits', location:'Yaoundé, Cameroon', snippet:'International conference on tropical diseases and global health in Yaoundé. Abstract submission open for health professionals and researchers.' },
  { tag:'medicine', category:'scholarship', title:'Fogarty International Center Global Health Fellowship 2026', source:'NIH Fogarty Center', link:'https://fic.nih.gov/fellowships', deadline:'April 1, 2026', eligibility:'African health scientists • PhD or MD • Research experience', benefits:'Research funding • US institution access • Stipend • Travel', location:'USA / Cameroon', snippet:'NIH Fogarty offers research fellowships for Cameroonian health scientists. Covers research costs, stipend and travel to US partner institutions.' },
  { tag:'medicine', category:'internship',  title:'MSF Medical Internship – Cameroon Field 2026', source:'Médecins Sans Frontières', link:'https://msf.org/internships', deadline:null, eligibility:'Final-year medical student or recent graduate • French/English', benefits:'Stipend • Field experience • MSF certification • Career development', location:'Cameroon (field)', snippet:'MSF recruiting medical interns for field operations in Cameroon. 3-month placement with stipend. Invaluable humanitarian medicine experience.' },
  { tag:'medicine', category:'competition', title:'Wellcome Trust Africa Biomedical Research Award 2026', source:'Wellcome Trust', link:'https://wellcome.org/africa-awards', deadline:'May 15, 2026', eligibility:'Early-career African biomedical scientists • PhD required', benefits:'Up to £500,000 funding • 5-year research support • Mentorship', location:'UK / Africa', snippet:'Wellcome Trust offers major research awards for early-career African biomedical scientists. Up to £500,000 over 5 years for transformative research.' },
  { tag:'medicine', category:'scholarship', title:'AFENET Field Epidemiology Training – Cameroon 2026', source:'AFENET', link:'https://afenet.net/training', deadline:'March 2026', eligibility:'Health workers • Bachelor\'s in health science • Cameroonian', benefits:'2-year programme • Stipend • WHO certification • Career placement', location:'Yaoundé, Cameroon', snippet:'AFENET Field Epidemiology Training Program for Cameroonian health workers. 2 years covering outbreak response, surveillance and data analysis.' },

  // ── ENGINEERING ─────────────────────────────────────────────────────────────
  { tag:'engineering', category:'internship',  title:'Shell Graduate Internship – Cameroon 2026', source:'Shell Cameroon', link:'https://shell.com/careers/internships', deadline:'June 28, 2026', eligibility:'Final-year or recent graduate • Engineering degree • GPA 3.0+', benefits:'Competitive stipend • Housing • Mentorship • Return offer potential', location:'Douala, Cameroon', snippet:'Shell Cameroon offers structured graduate internships in petroleum, mechanical and chemical engineering. 6-month paid placement with real projects.' },
  { tag:'engineering', category:'scholarship', title:'African Union Engineering Scholarship 2026', source:'African Union Commission', link:'https://au.int/scholarships/engineering', deadline:'April 30, 2026', eligibility:'African engineering students • Top academic record', benefits:'Full tuition • Stipend • Housing • Leadership development', location:'Various partner universities', snippet:'AU Commission scholarships for African engineering students at top universities. Covers tuition, stipend and housing. Cameroon nationals eligible.' },
  { tag:'engineering', category:'competition', title:'Young Engineers Africa Challenge 2026', source:'Young Engineers Africa', link:'https://youngengineers.africa/challenge', deadline:'June 30, 2026', eligibility:'African engineers • Age 18-30 • Any engineering discipline', benefits:'$20,000 prizes • Mentorship • Media coverage • Industry connections', location:'Pan-Africa', snippet:'Competition for African engineers to design innovative solutions for continental challenges. $20,000 in prizes and mentorship from industry leaders.' },
  { tag:'engineering', category:'job',         title:'Civil Engineer – Cameroon Infrastructure Projects', source:'JobsInAfrica CM', link:'https://jobsinafrica.cm/civil-engineer', deadline:null, eligibility:'Civil engineering degree • 3+ years experience', benefits:'Competitive salary • Transport • Insurance • Growth opportunities', location:'Yaoundé / Douala / Bamenda', snippet:'Major infrastructure company hiring civil engineers for road and bridge projects across Cameroon. Multiple positions available in key cities.' },
  { tag:'engineering', category:'scholarship', title:'DAAD Engineering Master\'s Scholarship 2026 – Germany', source:'DAAD Germany', link:'https://daad.de/engineering-masters', deadline:'October 2026', eligibility:'Engineering degree • Under 36 • Cameroonian national', benefits:'€934 monthly • Travel • Health insurance • Study allowance', location:'Germany', snippet:'DAAD fully funded scholarships for Cameroonian engineers to pursue Master\'s in Germany. Civil, electrical, mechanical and petroleum engineering.' },
  { tag:'engineering', category:'event',       title:'Cameroon Engineering Summit 2026', source:'Engineering Summit CM', link:'https://engineeringsummit.cm', deadline:null, eligibility:'Engineers, contractors and students welcome', benefits:'CPD credits • Networking • Industry insights • Student rates', location:'Yaoundé, Cameroon', snippet:'Annual summit for Cameroonian engineers covering infrastructure, energy and urban development. Student registration available at reduced rates.' },
  { tag:'engineering', category:'internship',  title:'ENEO Cameroon Electrical Engineering Internship 2026', source:'ENEO Cameroon', link:'https://eneo.cm/careers', deadline:null, eligibility:'Electrical engineering student • Final year • Cameroonian', benefits:'Monthly allowance • Field experience • Certificate', location:'Nationwide, Cameroon', snippet:'ENEO Cameroon recruiting electrical engineering interns for its power distribution network. Hands-on experience across all regions of Cameroon.' },
  { tag:'engineering', category:'competition', title:'Bridge Africa Engineering Competition 2026', source:'Bridge Africa', link:'https://bridgeafrica.org/competition', deadline:'May 1, 2026', eligibility:'Engineering students and professionals • Teams or individuals', benefits:'$15,000 prize • Incubation • Infrastructure contract opportunities', location:'Pan-Africa', snippet:'Design sustainable infrastructure solutions for rural Cameroon. $15,000 grand prize with potential infrastructure implementation contract.' },
  { tag:'engineering', category:'scholarship', title:'Japan-Africa Engineering Scholarship 2026 – JICA', source:'JICA Japan', link:'https://jica.go.jp/scholarships/engineering', deadline:'March 2026', eligibility:'Engineering degree • Under 40 • Cameroonian government employee preferred', benefits:'Full scholarship • Monthly allowance • Housing • Return flight', location:'Japan', snippet:'JICA scholarships for Cameroonian engineers to study in Japan. Covers tuition, accommodation and monthly allowance. Master\'s level programs.' },
  { tag:'engineering', category:'job',         title:'Petroleum Engineer – Perenco Cameroon', source:'Perenco Cameroon', link:'https://perenco.com/careers/cameroon', deadline:null, eligibility:'Petroleum or chemical engineering degree • 2+ years preferred', benefits:'Competitive expat package • Housing • Insurance • Career growth', location:'Douala / Offshore Cameroon', snippet:'Perenco Cameroon hiring petroleum engineers for offshore operations. Degree in petroleum or chemical engineering. Competitive expat compensation package.' },

  // ── LAW ─────────────────────────────────────────────────────────────────────
  { tag:'law', category:'scholarship', title:'Fulbright Foreign Student Program – Law 2026', source:'Fulbright Commission', link:'https://fulbright.org/cameroon', deadline:'October 2025', eligibility:'Cameroonian national • LLB • Leadership potential • English proficiency', benefits:'Full tuition • Stipend • Airfare • Health insurance', location:'United States', snippet:'Fulbright scholarships for Cameroonian law students and legal professionals to study LLM programs at top US law schools. Fully funded.' },
  { tag:'law', category:'internship',  title:'ICC Internship – International Criminal Law 2026', source:'International Criminal Court', link:'https://icc-cpi.int/internships', deadline:null, eligibility:'Law student or graduate • French or English fluency', benefits:'Stipend • ICC experience • Networking • Certificate', location:'The Hague, Netherlands', snippet:'ICC internships for law students from Africa. Positions in prosecution, defense and registry. Rolling admissions, French or English required.' },
  { tag:'law', category:'competition', title:'Philip C. Jessup Moot Court – Cameroon 2026', source:'ILSA', link:'https://ilsa.org/jessup', deadline:'January 2026', eligibility:'Law school teams • Any year of study', benefits:'International competition • Travel • Prizes • Prestige', location:'Washington DC / Cameroon qualifier', snippet:'World\'s largest moot court competition. Cameroon law schools register teams for national qualifier. Winners advance to international rounds in DC.' },
  { tag:'law', category:'job',         title:'Legal Officer – UN Cameroon 2026', source:'UN Careers', link:'https://careers.un.org/cameroon', deadline:null, eligibility:'LLM in international law • 3+ years • French/English', benefits:'P3 UN salary • Benefits • International career • Security', location:'Yaoundé, Cameroon', snippet:'United Nations Cameroon recruiting Legal Officer for Yaoundé operations. LLM in international law required. P3 level with competitive UN compensation.' },
  { tag:'law', category:'scholarship', title:'Commonwealth Scholarship – Law 2026 UK', source:'Commonwealth Scholarship Commission', link:'https://cscuk.fcdo.gov.uk/law', deadline:'December 2025', eligibility:'Cameroonian national • LLB • Under 35 • Strong academic record', benefits:'Full tuition • Airfare • Living allowance • Visa support', location:'United Kingdom', snippet:'Commonwealth scholarships for Cameroonian law students to pursue LLM degrees at UK universities. Fully funded including tuition, airfare and living allowance.' },
  { tag:'law', category:'event',       title:'African Law Forum Yaoundé 2026', source:'African Law Forum', link:'https://africanlawforum.org/yaounde', deadline:null, eligibility:'Lawyers, judges and law students welcome', benefits:'CPD credits • Networking • Publication opportunity', location:'Yaoundé, Cameroon', snippet:'Annual conference bringing together lawyers, judges and scholars from across Africa. Student registration at reduced rates. May 2026.' },
  { tag:'law', category:'internship',  title:'African Court on Human Rights Internship 2026', source:'African Court', link:'https://african-court.org/internships', deadline:'March 2026', eligibility:'African law graduate • French or English', benefits:'Accommodation covered • 3-month placement • Certificate', location:'Arusha, Tanzania', snippet:'African Court on Human and Peoples\' Rights offers internships for African law graduates. 3-month placement with accommodation covered.' },
  { tag:'law', category:'job',         title:'Legal Counsel – Cameroon Development Corporation', source:'CDC Cameroon', link:'https://cdc-cameroon.net/careers', deadline:null, eligibility:'LLB required • LLM preferred • 5+ years corporate law', benefits:'Competitive government salary • Benefits • Stability', location:'Limbe, Cameroon', snippet:'CDC Cameroon seeking Legal Counsel for corporate legal department. LLB required, LLM preferred. 5+ years experience in corporate and commercial law.' },
  { tag:'law', category:'competition', title:'African Human Rights Essay Competition 2026', source:'AHRLJ', link:'https://ahrlj.up.ac.za/essay-competition', deadline:'June 2026', eligibility:'African law students and young lawyers • Under 35', benefits:'Cash prize • Publication • Conference invitation', location:'Online', snippet:'Annual essay competition on African human rights law. Cash prizes, publication in peer-reviewed journal and invitation to African Human Rights conference.' },
  { tag:'law', category:'scholarship', title:'OHCHR Human Rights Fellowship – Africa 2026', source:'OHCHR', link:'https://ohchr.org/fellowships/africa', deadline:'February 28, 2026', eligibility:'African human rights defenders and lawyers • LLB minimum', benefits:'3-month Geneva placement • Travel • Accommodation • Stipend', location:'Geneva, Switzerland', snippet:'OHCHR offers fellowships for African human rights lawyers. 3-month placement in Geneva with travel, accommodation and stipend covered.' },

  // ── EDUCATION ───────────────────────────────────────────────────────────────
  { tag:'education', category:'scholarship', title:'Commonwealth Distance Learning Scholarships 2026', source:'Commonwealth Scholarship Commission', link:'https://cscuk.fcdo.gov.uk/distance-learning', deadline:'March 2026', eligibility:'Cameroonian teachers and education professionals • Bachelor\'s degree', benefits:'Full distance learning tuition • Study materials • UK university degree', location:'Online (UK universities)', snippet:'Commonwealth scholarships for Cameroonian teachers to pursue distance learning Master\'s degrees at UK universities. Fully funded.' },
  { tag:'education', category:'internship',  title:'UNESCO Education Internship – Yaoundé 2026', source:'UNESCO Cameroon', link:'https://unesco.org/internships/cameroon', deadline:null, eligibility:'Master\'s student in education • French/English fluency', benefits:'Paid stipend • UN experience • Certificate • Networking', location:'Yaoundé, Cameroon', snippet:'UNESCO Cameroon internships in education policy, curriculum development and literacy programs. 3-6 month paid placement for Master\'s students.' },
  { tag:'education', category:'competition', title:'Education Innovation Challenge Cameroon 2026', source:'EdChallenge CM', link:'https://edchallenge.cm', deadline:'May 2026', eligibility:'Teachers, students and entrepreneurs • Cameroonians', benefits:'10 million FCFA prize • Incubation • Media coverage', location:'Cameroon', snippet:'Submit innovative education solutions for Cameroon\'s schools. EdTech and pedagogy innovation tracks. 10M FCFA prize for best solution.' },
  { tag:'education', category:'job',         title:'Primary School Teacher – APEE Schools Network 2026', source:'APEE Cameroon', link:'https://apee.cm/jobs', deadline:'February 2026', eligibility:'DIPES I or equivalent • Cameroonian national', benefits:'Competitive salary • Housing allowance • Professional development', location:'Yaoundé / Douala', snippet:'APEE school network hiring primary school teachers for 2026-2027 academic year. DIPES I or equivalent required. Applications open February 2026.' },
  { tag:'education', category:'scholarship', title:'African Development Bank Education Scholarship 2026', source:'African Development Bank', link:'https://afdb.org/education-scholarship', deadline:'April 2026', eligibility:'African students • Education policy or management postgrad', benefits:'Full scholarship • Stipend • Housing • Mentorship', location:'Various', snippet:'AfDB scholarships for African students to study education policy and management at postgraduate level. Cameroon nationals fully eligible.' },
  { tag:'education', category:'event',       title:'EdTech Africa Conference Douala 2026', source:'EdTech Africa', link:'https://edtechafrica.org/douala', deadline:null, eligibility:'Open to educators, tech professionals and students', benefits:'Networking • Workshops • Startup pitches • Student rates', location:'Douala, Cameroon', snippet:'EdTech Africa conference in Douala explores technology in education. Workshops, startup pitches and policy discussions. Student tickets available.' },
  { tag:'education', category:'internship',  title:'Teach For Cameroon Fellowship 2026', source:'Teach For Cameroon', link:'https://teachforcameroon.org/fellowship', deadline:null, eligibility:'Recent graduate • Any discipline • Leadership potential', benefits:'Monthly stipend • Professional development • Leadership training • Alumni network', location:'Underserved schools, Cameroon', snippet:'Teach For Cameroon recruits passionate graduates to teach in underserved schools for 2 years. Monthly stipend, professional development and leadership training.' },
  { tag:'education', category:'scholarship', title:'French Language Teaching Assistant – Campus France 2026', source:'Campus France', link:'https://campusfrance.org/teaching-assistant', deadline:'January 2026', eligibility:'Cameroonian French/English teachers • Bachelor\'s minimum', benefits:'7-month contract • Accommodation • Monthly stipend • French experience', location:'France', snippet:'Campus France teaching assistant positions in France for Cameroonian teachers. 7-month contract with accommodation and stipend.' },
  { tag:'education', category:'job',         title:'UNICEF Education Specialist – Cameroon 2026', source:'UNICEF', link:'https://unicef.org/careers/education-specialist', deadline:null, eligibility:'Master\'s in education • 5+ years experience • French/English', benefits:'P3 UN salary • Benefits • International career', location:'Yaoundé, Cameroon', snippet:'UNICEF Cameroon hiring Education Specialist to support back-to-school programs in conflict-affected regions. P3 level position.' },
  { tag:'education', category:'competition', title:'Global Teacher Prize – Cameroon Nominations 2026', source:'Varkey Foundation', link:'https://globalteacherprize.org', deadline:'March 2026', eligibility:'Practising teachers • 5+ years experience • Nominated or self-nominated', benefits:'$1 million prize • Global recognition • Community for 50 finalists', location:'Global', snippet:'Nominate an exceptional Cameroonian teacher for the $1 million Global Teacher Prize. Self-nominations accepted. 50 finalists receive global recognition.' },

  // ── ENTREPRENEURSHIP ────────────────────────────────────────────────────────
  { tag:'entrepreneurship', category:'competition', title:'Tony Elumelu Foundation Entrepreneurship Program 2026', source:'Tony Elumelu Foundation', link:'https://tonyelumelufoundation.org/teep', deadline:'March 1, 2026', eligibility:'African national • Early-stage business • Any sector', benefits:'$5,000 seed capital • 12-week training • Mentorship • Network', location:'Online', snippet:'Africa\'s flagship entrepreneurship programme. 1,000 entrepreneurs selected. $5,000 non-refundable seed capital plus mentorship and training.' },
  { tag:'entrepreneurship', category:'event',       title:'Cameroon Startup Ecosystem Summit 2026', source:'Startups CM', link:'https://startups.cm/summit', deadline:null, eligibility:'Startups, investors and ecosystem builders', benefits:'Pitching sessions • Workshops • Investor meetings • Networking', location:'Douala, Cameroon', snippet:'Annual summit for Cameroonian entrepreneurs and investors. Pitching sessions, workshops and networking. Register for the 2026 cohort.' },
  { tag:'entrepreneurship', category:'scholarship', title:'YouthBiz Africa Scholarship 2026', source:'YouthBiz Africa', link:'https://youthbizafrica.org/scholarship', deadline:'March 30, 2026', eligibility:'Cameroonian entrepreneurs • Age 18-30', benefits:'Full business school tuition • Mentorship • Alumni network', location:'Various partner universities', snippet:'Scholarship for young Cameroonian entrepreneurs to attend business school. Covers tuition for entrepreneurship programs at partner universities.' },
  { tag:'entrepreneurship', category:'competition', title:'African Entrepreneurship Award 2026 – BMCE Bank', source:'BMCE Bank', link:'https://africanentrepreneurshipaward.com', deadline:'September 2026', eligibility:'African entrepreneurs • Scalable business model • Any sector', benefits:'$1.2M total prizes • Mentorship • Media coverage • Investor access', location:'Pan-Africa', snippet:'BMCE Bank African Entrepreneurship Award. $1.2M in prizes for African entrepreneurs with scalable and impactful businesses. Cameroon applicants welcome.' },
  { tag:'entrepreneurship', category:'internship',  title:'Business Incubator Coordinator – Yaoundé 2026', source:'Jobs CM', link:'https://jobs.cm/incubator-coordinator', deadline:null, eligibility:'Entrepreneurship or business background • 2+ years', benefits:'Competitive salary • Startup exposure • Growth potential', location:'Yaoundé, Cameroon', snippet:'Tech incubator in Yaoundé hiring Business Incubator Coordinator to support early-stage startups. Entrepreneurship background required.' },
  { tag:'entrepreneurship', category:'event',       title:'Startup Grind Douala – Monthly Meetup 2026', source:'Startup Grind Douala', link:'https://startupgrind.com/douala', deadline:null, eligibility:'Open to all entrepreneurs and startup enthusiasts', benefits:'Founder stories • Investor pitches • Community building • Free entry', location:'Douala, Cameroon', snippet:'Monthly startup networking event in Douala featuring founder stories, investor pitches and community building. Free to attend. Every second Saturday.' },
  { tag:'entrepreneurship', category:'competition', title:'Seedstars Cameroon 2026', source:'Seedstars', link:'https://seedstars.com/cameroon', deadline:'May 31, 2026', eligibility:'Tech startup • 0-3 years old • Cameroonian founders', benefits:'Up to $500,000 equity • Global network • Mentorship', location:'Douala, Cameroon', snippet:'Seedstars searching for best startup in Cameroon. Winners receive equity investment up to $500,000 and access to global Seedstars investor network.' },
  { tag:'entrepreneurship', category:'scholarship', title:'AFDB Entrepreneurship Hub Cameroon Cohort 2026', source:'African Development Bank', link:'https://afdb.org/entrepreneurship-hub', deadline:'April 2026', eligibility:'Cameroonian startups • Any sector • Early stage', benefits:'6-month incubation • Equity-free funding • Market access • Mentorship', location:'Cameroon', snippet:'AfDB entrepreneurship hub in Cameroon. 50 startups selected for 6-month incubation, equity-free funding and market access support.' },
  { tag:'entrepreneurship', category:'competition', title:'Hult Prize Cameroon 2026', source:'Hult Prize', link:'https://hultprize.org/cameroon', deadline:null, eligibility:'University students • Teams of 4 • Any discipline', benefits:'$1M global prize • Incubation • Mentorship • Media', location:'Cameroon universities', snippet:'World\'s largest student social entrepreneurship competition. Cameroon campus competitions at universities nationwide. Compete for $1 million prize.' },
  { tag:'entrepreneurship', category:'event',       title:'Women Entrepreneurship Forum Cameroon 2026', source:'WEF Cameroon', link:'https://wefcameroon.org/forum', deadline:null, eligibility:'Women entrepreneurs • All sectors • All ages', benefits:'5M FCFA grants • Mentorship • Networking • Media coverage', location:'Yaoundé, Cameroon', snippet:'Annual forum for women entrepreneurs in Cameroon. 5 million FCFA grants available for women-led businesses in agriculture, tech and services.' },

  // ── DATA SCIENCE / AI ────────────────────────────────────────────────────────
  { tag:'data_science', category:'scholarship', title:'Google Data Analytics Certificate Scholarship – Africa 2026', source:'Google Africa', link:'https://grow.google/africa/data-analytics', deadline:'March 2026', eligibility:'African national • Age 18+ • Any background', benefits:'Free certification • Google credential • Job placement support', location:'Online', snippet:'Google offering 50,000 scholarships for the Data Analytics Certificate to African students. Covers full cost. Cameroon applicants eligible.' },
  { tag:'data_science', category:'competition', title:'Zindi Africa Data Science Competition 2026 – Cameroon Health', source:'Zindi Africa', link:'https://zindi.africa/competitions/cameroon-health', deadline:'March 31, 2026', eligibility:'Open to all skill levels • Individual or team', benefits:'$5,000 prize pool • Zindi ranking • Career visibility', location:'Online', snippet:'Zindi hosts data science competition using Cameroon health data to predict disease outbreaks. $5,000 prize pool. Open to all skill levels.' },
  { tag:'data_science', category:'scholarship', title:'AIMS Cameroon Data Science Master\'s Scholarship 2026', source:'AIMS Cameroon', link:'https://aims.cm/masters', deadline:'May 31, 2026', eligibility:'Bachelor\'s in mathematics, CS or statistics • African national', benefits:'Full scholarship • Stipend • Housing • Research support', location:'Limbe, Cameroon', snippet:'African Institute for Mathematical Sciences Cameroon offers full scholarships for Master\'s in Mathematical Sciences with data science specialization.' },
  { tag:'data_science', category:'internship',  title:'Data Science Intern – AfricaData Hub 2026', source:'AfricaData Hub', link:'https://africadatahub.org/internships', deadline:null, eligibility:'Statistics, CS or data science student • Any level', benefits:'Paid remote internship • Real datasets • Certificate • Mentorship', location:'Remote', snippet:'AfricaData Hub offers remote data science internships. Work on real-world datasets from health, agriculture and finance sectors across Africa.' },
  { tag:'data_science', category:'event',       title:'IndabaX Cameroon 2026 – Deep Learning Conference', source:'IndabaX Cameroon', link:'https://indabaxcameroon.org', deadline:'May 2026', eligibility:'AI/ML practitioners and students • Open registration', benefits:'Tutorials • Research presentations • Networking • Certificates', location:'Yaoundé, Cameroon', snippet:'IndabaX Cameroon brings together AI and ML practitioners for a 3-day conference. Tutorials, research presentations and networking. May 2026.' },
  { tag:'data_science', category:'scholarship', title:'AI4D Africa Scholarship Program 2026', source:'AI4D Africa', link:'https://ai4d.ai/scholarships', deadline:'April 2026', eligibility:'African researchers • AI/data science for development focus', benefits:'Up to $50,000 research grant • Mentorship • Publication support', location:'Pan-Africa', snippet:'AI4D Africa scholarships for researchers working on AI for development. Up to $50,000 research grant for Cameroon applicants.' },
  { tag:'data_science', category:'job',         title:'Data Analyst – World Food Programme Cameroon', source:'WFP', link:'https://wfp.org/careers/cameroon', deadline:'February 2026', eligibility:'Statistics or data science degree • Excel, Power BI, SQL', benefits:'Competitive UN salary • Benefits • International experience', location:'Yaoundé, Cameroon', snippet:'WFP Cameroon recruiting Data Analyst for food security monitoring. Excel, Power BI and SQL required. Based in Yaoundé with competitive UN salary.' },
  { tag:'data_science', category:'competition', title:'DataFest Africa 2026 – Cameroon Edition', source:'DataFest Africa', link:'https://datafest.africa/cameroon', deadline:'April 2026', eligibility:'Students and professionals • Teams or individual • Any level', benefits:'$10,000 prizes • Networking • Career visibility', location:'Cameroon', snippet:'DataFest Africa annual data science hackathon in Cameroon. Teams solve real problems using data. $10,000 in prizes. Open to all skill levels.' },
  { tag:'data_science', category:'scholarship', title:'Google Research Africa Fellowship 2026', source:'Google Research Africa', link:'https://research.google/programs/africa-fellowship', deadline:null, eligibility:'PhD students and researchers • ML/AI focus • African institution', benefits:'Research funding • Google mentorship • Collaboration opportunities', location:'Online / Africa', snippet:'Google Research Africa Fellowship supports PhD students working on machine learning and AI. Annual application cycle. Cameroon researchers welcome.' },
  { tag:'data_science', category:'job',         title:'ML Engineer – Cameroon Revenue Authority', source:'DGI Cameroon', link:'https://dgi.cm/careers', deadline:null, eligibility:'Master\'s in data science or statistics • Python, R, SQL', benefits:'Government salary scale • Stability • Professional development', location:'Yaoundé, Cameroon', snippet:'Cameroon Revenue Authority hiring Data Scientists and ML Engineers to improve tax compliance analytics. Python, R and SQL required.' },

  // ── ARTS ─────────────────────────────────────────────────────────────────────
  { tag:'arts', category:'scholarship', title:'African Cultural Fund Arts Scholarship 2026', source:'African Cultural Fund', link:'https://africanculturalfund.org/scholarships', deadline:'April 2026', eligibility:'African artists • Any medium • Portfolio required', benefits:'$5,000 grant • Residency • Exhibition opportunity • Mentorship', location:'Pan-Africa', snippet:'African Cultural Fund scholarships for emerging African artists. $5,000 grant plus residency and exhibition opportunity. Portfolio submission required.' },
  { tag:'arts', category:'competition', title:'Cameroon Arts Festival Competition 2026', source:'MINAC Cameroon', link:'https://minac.cm/festival', deadline:'March 2026', eligibility:'Cameroonian artists • All disciplines • All ages', benefits:'Cash prizes • National exhibition • Media coverage', location:'Yaoundé, Cameroon', snippet:'National arts competition across visual arts, music, dance and literature. Cash prizes and national exhibition for winners. All Cameroonian artists welcome.' },
  { tag:'arts', category:'internship',  title:'Cultural Programme Intern – Institut Français Cameroun', source:'Institut Français Cameroun', link:'https://institutfrancais-cameroun.com/internships', deadline:null, eligibility:'Arts or cultural management student • French fluency', benefits:'Stipend • Cultural exposure • Networking • Certificate', location:'Yaoundé / Douala', snippet:'Institut Français Cameroun internships in cultural programming, event management and artistic direction. French fluency required.' },
  { tag:'arts', category:'event',       title:'Douala Art Week 2026', source:'Doual\'art', link:'https://doualart.org/art-week', deadline:null, eligibility:'Open to artists, collectors and art lovers', benefits:'Networking • Exhibition • Sales opportunities • Media coverage', location:'Douala, Cameroon', snippet:'Annual art week in Douala featuring exhibitions, performances and artist talks. One of West Africa\'s premier contemporary art events.' },
  { tag:'arts', category:'scholarship', title:'Civitella Ranieri Artist Residency Fellowship 2026', source:'Civitella Ranieri Foundation', link:'https://civitella.org/fellowships', deadline:'January 2026', eligibility:'Professional artists and writers • Portfolio required • Any nationality', benefits:'6-week residency • Studio • Accommodation • Materials stipend', location:'Umbria, Italy', snippet:'Prestigious artist residency in Italy for professional artists and writers. 6 weeks with studio, accommodation and materials stipend fully covered.' },
  { tag:'arts', category:'competition', title:'African Photography Award 2026', source:'Nando\'s African Photography', link:'https://africaphotographyaward.com', deadline:'June 2026', eligibility:'African photographers • Any age • Digital or film', benefits:'$10,000 prize • Exhibition • Publication • Career platform', location:'Online / Pan-Africa', snippet:'Premier photography competition celebrating African stories. $10,000 prize, international exhibition and publication in major photography magazine.' },
  { tag:'arts', category:'job',         title:'Graphic Designer – Cameroon Broadcasting Corporation', source:'CRTV Cameroon', link:'https://crtv.cm/careers', deadline:null, eligibility:'Graphic design degree • Adobe Creative Suite • Portfolio', benefits:'Government salary • Benefits • Creative environment', location:'Yaoundé, Cameroon', snippet:'CRTV Cameroon hiring Graphic Designer for its digital media department. Adobe Creative Suite proficiency required. Strong portfolio needed.' },
  { tag:'arts', category:'scholarship', title:'Rolex Mentor and Protégé Arts Initiative 2026', source:'Rolex', link:'https://rolexmentorprotege.com', deadline:'March 2026', eligibility:'Emerging artists • Age 25-45 • Any discipline • Portfolio', benefits:'Mentorship from master artist • Project grant • Global platform', location:'Global', snippet:'Rolex pairs emerging artists with masters in their field for 2-year mentorship. Project grant and global platform included. Cameroon artists eligible.' },
  { tag:'arts', category:'internship',  title:'Film Production Intern – Cameroon Film Festival 2026', source:'CamFilmFest', link:'https://cameroonfilmfestival.com/internships', deadline:null, eligibility:'Film studies student or recent graduate', benefits:'Festival experience • Industry networking • Certificate', location:'Yaoundé, Cameroon', snippet:'Cameroon Film Festival internships in production, programming and communications. Invaluable industry experience and networking with African filmmakers.' },
  { tag:'arts', category:'competition', title:'African Literature Prize 2026 – Short Story', source:'Writivism', link:'https://writivism.org/prize', deadline:'April 2026', eligibility:'African writers • Short stories 3,000-6,000 words • Any language', benefits:'$5,000 prize • Publication • International platform', location:'Online', snippet:'Writivism African Literature Prize for short stories. $5,000 prize and publication in leading African literary journal. Open to all African writers.' },

  // ── AGRICULTURE ─────────────────────────────────────────────────────────────
  { tag:'agriculture', category:'scholarship', title:'FAO Young Professionals Program 2026', source:'FAO', link:'https://fao.org/employment/young-professionals', deadline:'February 2026', eligibility:'Agriculture or food science degree • Under 32 • Cameroonian national', benefits:'Competitive UN salary • Benefits • International career • Field experience', location:'Rome / Field offices', snippet:'FAO Young Professionals Program for Cameroonians with agriculture degrees. Competitive UN salary and international career development opportunities.' },
  { tag:'agriculture', category:'competition', title:'Cameroon Agricultural Innovation Challenge 2026', source:'MINADER Cameroon', link:'https://minader.cm/innovation', deadline:'May 2026', eligibility:'Cameroonian farmers, students and entrepreneurs', benefits:'15 million FCFA prizes • Incubation • Market access', location:'Cameroon', snippet:'National agricultural innovation competition. Solutions for crop disease, irrigation, storage and market access. 15M FCFA in prizes.' },
  { tag:'agriculture', category:'internship',  title:'Agri-Business Intern – CDC Cameroon 2026', source:'CDC Cameroon', link:'https://cdc-cameroon.net/careers/internships', deadline:null, eligibility:'Agriculture or agri-business student • Final year', benefits:'Paid stipend • Field experience • Certificate • Return offer', location:'Fako Division, Cameroon', snippet:'Cameroon Development Corporation agricultural internships in palm oil, rubber and banana plantations. Hands-on agri-business experience.' },
  { tag:'agriculture', category:'scholarship', title:'Borlaug LEAP Fellowship – Africa 2026', source:'CIMMYT', link:'https://borlaug-leap.cimmyt.org', deadline:'March 2026', eligibility:'Agriculture PhD student • African institution • Research focus', benefits:'$12,000 fellowship • Mentorship • Research travel • Publication', location:'Various (Mexico/Africa)', snippet:'Borlaug LEAP Fellowship for African PhD students in agriculture. $12,000 plus mentorship from world-leading plant scientists at CIMMYT.' },
  { tag:'agriculture', category:'event',       title:'Cameroon Agricultural Expo 2026', source:'MINADER', link:'https://agriexpo.cm', deadline:null, eligibility:'Open to farmers, researchers and agri-businesses', benefits:'Networking • Market access • Technology showcase', location:'Yaoundé, Cameroon', snippet:'Annual agricultural exposition showcasing Cameroon\'s farming innovations. Networking with buyers, investors and research institutions.' },
  { tag:'agriculture', category:'job',         title:'Agronomist – World Food Programme Cameroon', source:'WFP Cameroon', link:'https://wfp.org/careers/cameroon/agronomist', deadline:null, eligibility:'Agronomy or agriculture degree • 3+ years field experience', benefits:'UN salary • Benefits • Field work • International exposure', location:'Maroua / Bertoua, Cameroon', snippet:'WFP Cameroon hiring Agronomist for food security programs in Far North and East regions. 3+ years field experience in smallholder agriculture.' },
  { tag:'agriculture', category:'scholarship', title:'African Women in Agri-Business Scholarship 2026', source:'AGRA', link:'https://agra.org/scholarships/women', deadline:'April 2026', eligibility:'African women • Agriculture or agri-business • Bachelor\'s minimum', benefits:'Full scholarship • Mentorship • Network • Stipend', location:'Various African universities', snippet:'AGRA scholarships for African women pursuing advanced degrees in agriculture and agri-business. Full scholarship with mentorship and professional network.' },
  { tag:'agriculture', category:'internship',  title:'Climate-Smart Agriculture Intern – GIZ Cameroon 2026', source:'GIZ Germany', link:'https://giz.de/cameroon/internships', deadline:null, eligibility:'Agriculture or environment student • French/English', benefits:'Stipend • International organization experience • Certificate', location:'Yaoundé, Cameroon', snippet:'GIZ Cameroon climate-smart agriculture internships. Support implementation of sustainable farming practices across Cameroon\'s regions.' },
  { tag:'agriculture', category:'competition', title:'Youth Agripreneur Challenge Cameroon 2026', source:'IITA Youth Agripreneurs', link:'https://iita.org/youth-agripreneurs', deadline:'June 2026', eligibility:'Youth 18-35 • Agricultural enterprise • Cameroonian', benefits:'$10,000 prize • Incubation • Training • Market linkages', location:'Cameroon', snippet:'IITA Youth Agripreneur Challenge for young Cameroonian agricultural entrepreneurs. $10,000 prize with incubation, training and market linkage support.' },
  { tag:'agriculture', category:'scholarship', title:'RUFORUM Graduate Fellowship 2026', source:'RUFORUM', link:'https://ruforum.org/fellowships', deadline:'March 2026', eligibility:'Agriculture Master\'s or PhD • African university student', benefits:'Full scholarship • Research support • Network • Travel', location:'Various African universities', snippet:'RUFORUM Graduate Fellowship for African agriculture students. Full scholarship with research support and access to pan-African agriculture network.' },

  // ── RESEARCH ─────────────────────────────────────────────────────────────────
  { tag:'research', category:'scholarship', title:'Carnegie African Diaspora Fellowship 2026', source:'Carnegie Corporation', link:'https://cadfellowship.org', deadline:'March 2026', eligibility:'African-born academics at US/Canadian institutions • PhD', benefits:'Research visit funding • Collaboration support • $5,000 grant', location:'Africa / North America', snippet:'Carnegie African Diaspora Fellowship connects African-born academics with African universities for collaborative research. $5,000 research grant.' },
  { tag:'research', category:'competition', title:'Next Einstein Forum Science Leapfrogging Award 2026', source:'Next Einstein Forum', link:'https://nef.org/science-award', deadline:'April 2026', eligibility:'African scientists • Any discipline • Innovative research', benefits:'$100,000 award • Global platform • Research support', location:'Pan-Africa', snippet:'NEF Science Leapfrogging Award for African scientists solving continent-wide challenges. $100,000 prize and global platform for winners.' },
  { tag:'research', category:'internship',  title:'Research Intern – IRAD Cameroon 2026', source:'IRAD Cameroon', link:'https://irad.cm/internships', deadline:null, eligibility:'Science student • Any discipline • Cameroonian', benefits:'Research experience • Mentorship • Publication opportunity', location:'Yaoundé, Cameroon', snippet:'Institute for Agricultural Research for Development (IRAD) research internships for Cameroonian science students. Hands-on research experience.' },
  { tag:'research', category:'scholarship', title:'Wellcome Trust African Institutions Initiative 2026', source:'Wellcome Trust', link:'https://wellcome.org/african-institutions', deadline:'May 2026', eligibility:'African researchers • Any health-related discipline • Institution-based', benefits:'Up to £3M institutional grant • Capacity building • Equipment', location:'African institutions', snippet:'Wellcome Trust supports African research institutions. Grants up to £3M for capacity building, equipment and research programs. Cameroon institutions eligible.' },
  { tag:'research', category:'scholarship', title:'TWAS Research Grant – Sub-Saharan Africa 2026', source:'TWAS', link:'https://twas.org/grants', deadline:'March 2026', eligibility:'African researchers • PhD required • Developing country institution', benefits:'Up to $15,000 research grant • Equipment • Travel', location:'Cameroon institution-based', snippet:'TWAS grants for researchers at developing country institutions. Up to $15,000 for equipment, research costs and travel. Cameroon researchers eligible.' },
  { tag:'research', category:'event',       title:'African Research Universities Alliance Conference 2026', source:'ARUA', link:'https://arua.org.za/conference', deadline:null, eligibility:'Researchers and postgrad students at African universities', benefits:'Networking • Publication • Collaboration opportunities', location:'Pan-Africa', snippet:'ARUA annual conference connecting researchers across African universities. Networking, publication opportunities and collaborative research partnerships.' },
  { tag:'research', category:'job',         title:'Research Associate – IRIC Yaoundé 2026', source:'IRIC Cameroon', link:'https://iric.cm/careers', deadline:null, eligibility:'Master\'s or PhD in biomedical science • French/English', benefits:'Research salary • Lab access • Publication support', location:'Yaoundé, Cameroon', snippet:'Institute for Research in Immunology and Cancer of Cameroon hiring Research Associates. Master\'s or PhD in biomedical science required.' },
  { tag:'research', category:'competition', title:'L\'Oréal-UNESCO For Women in Science 2026 – Africa', source:'L\'Oréal Foundation', link:'https://forwomeninscience.com/africa', deadline:'June 2026', eligibility:'African women scientists • PhD • Under 40', benefits:'€15,000 fellowship • Global platform • Mentorship', location:'Pan-Africa', snippet:'L\'Oréal-UNESCO For Women in Science fellowships for African women researchers. €15,000 fellowship and global platform for outstanding science.' },
  { tag:'research', category:'internship',  title:'Research Intern – CIRCB Cameroon 2026', source:'CIRCB', link:'https://circb.cm/internships', deadline:null, eligibility:'Biomedical science student • Any level • Cameroonian', benefits:'Lab experience • Mentorship • Publication opportunity', location:'Yaoundé, Cameroon', snippet:'Chantal Biya International Reference Centre for HIV/AIDS research internships. Hands-on biomedical research experience in world-class facility.' },
  { tag:'research', category:'scholarship', title:'DAAD Research Scholarship – Africa 2026', source:'DAAD Germany', link:'https://daad.de/research-africa', deadline:'October 2026', eligibility:'African researchers • Master\'s minimum • Any discipline', benefits:'Full scholarship • Monthly stipend • Research support • Travel', location:'Germany', snippet:'DAAD research scholarships for African researchers to conduct studies at German universities and research institutes. All disciplines welcome.' },
];

export async function seedOpportunities() {
  // Group by tag
  const byTag = {};
  for (const opp of OPPORTUNITIES) {
    if (!byTag[opp.tag]) byTag[opp.tag] = [];
    byTag[opp.tag].push(opp);
  }

  const now = new Date().toISOString();
  // Set cache far in the future so it always serves (12h TTL from now)
  const cacheTime = new Date(Date.now() - 1000).toISOString(); // 1 second ago = within TTL

  for (const [tag, opps] of Object.entries(byTag)) {
    const processed = opps.map((o, idx) => ({
      id: `static-${tag}-${idx}`,
      title: o.title,
      link: o.link,
      snippet: o.snippet,
      description: o.snippet,
      source: o.source,
      tag,
      category: o.category,
      deadline: o.deadline || null,
      eligibility: o.eligibility || null,
      benefits: o.benefits || null,
      location: o.location || null,
      verified: true,
    }));

    const { error } = await supabase.from('lp_tag_cache').upsert(
      { tag, results: JSON.stringify(processed), cached_at: cacheTime },
      { onConflict: 'tag' }
    );
    if (error) console.error(`Seed error for ${tag}:`, error.message);
    else console.log(`[Seed] Seeded ${processed.length} opps for tag: ${tag}`);
  }
  console.log('[Seed] Static opportunity library seeded.');
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method === 'OPTIONS') return res.status(204).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  try {
    await seedOpportunities();
    return res.status(200).json({ ok: true, message: 'Opportunity library seeded.' });
  } catch (err) {
    console.error('Seed error:', err);
    return res.status(500).json({ error: err.message });
  }
}
